### ISSUE TITLE
Cloud Coders: Automate Virtual Machine Creation from Azure Cloud

### ISSUE THREAD

**Issue by VasudeoShruti** [VasudeoShruti/CloudCoders#2]
**This git issue captures the efforts in Automating Azure VM using Python.**

**What is Azure Virtual Machine?**

In Azure, a Virtual Machine (VM) is a software emulation of a physical machine that allows you to run various operating systems and applications. It provides you with the flexibility to create and manage a variety of virtual machines with different specifications, operating systems, and applications to meet your specific needs.

The Azure VM hierarchy includes the following components:

- **Subscription**: The highest-level container that holds your Azure resources and services.
- **Resource Group**: A logical container for grouping related Azure resources together.
- **Virtual Network**: A virtual network that connects Azure resources together and with your on-premises network.
- **Virtual Machine**: An instance of a virtual machine that runs your chosen operating system and applications.

Virtual machines in Azure are important because they provide a scalable and flexible infrastructure for running your applications and services in the cloud. You can create, configure, and manage virtual machines easily using Azure Portal, Azure PowerShell, or Azure CLI, depending on your preference. 

By leveraging Azure virtual machines, you can quickly provision and scale your computing resources up or down as needed, without having to worry about maintaining physical hardware or infrastructure. Additionally, Azure virtual machines support a wide range of operating systems, including Windows, Linux, and other open-source platforms, allowing you to choose the right environment for your application needs.

**Comment by AAYIRL** [comment]
**DAY 2**:

**TASK**: Adding various options for customizing the Virtual Machine Name and Storage Type

Added various option for changing the name of the resource group, the Virtual Machine Name and the Virtual Machine Storage   Type

_(**Refer the screenshots attached below)_
<img width="960" alt="Virtual_Machine_Provisioning_Form" src="https://user-images.githubusercontent.com/86376174/231354864-8b680981-c73a-4751-bde1-74f1c850d3c5.png">

**Comment by AAYIRL** [comment]
**DAY 3**

**TASK**: Did some exception handling and testing

Added some exception handling and tested the application to make sure it works correctly with the Frontend and the VM gets provisioned when the script is run.

_(**Refer the screenshots attached below)_
<img width="671" alt="VM_Provisioning" src="https://user-images.githubusercontent.com/86376174/231657376-45f85587-f0b2-420b-8b00-d00786e6811e.png">

**Comment by VasudeoShruti** [comment]
**SUMMARY:**

- This git issue is used for tracking the efforts for automating VM creation on Azure using Python code. 
- The required test results has been attached with the git issue.
- The working code has been pushed to git repo: https://github.com/VasudeoShruti/CloudCoders/pull/7

**Closing the issue since the needful has been done.**
