### ISSUE TITLE
Cloud Coders: Automate Storage Creation from Azure Cloud

### ISSUE THREAD

**Issue by VasudeoShruti** [VasudeoShruti/CloudCoders#3]
**This git issue captures the efforts in Automating Azure Storage using Python.**

### **Azure Storage Automation** 

The **Azure Storage** platform is Microsoft's cloud storage solution for modern data storage scenarios. Azure Storage offers highly available, massively scalable, durable, and secure storage for a variety of data objects in the cloud.

Creating a script will help the user to automate the Storage creation process and provision the Storage Account and further create a Data Service under the Storage Account.

**Comment by VasudeoShruti** [comment]
Marking it as duplicate & closing this.

**Comment by Aman-Surkar** [comment]
***DAY 1***

TASK: Writing a python script to Automate Azure Storage Account.

Assembled and installed all the required Azure Python Libraries. Writing Python Script to create Resource Group.
```
def create_rg(rg_name, sub_id):
    subscription_id = sub_id
    resource_client = ResourceManagementClient(credential, subscription_id)
    RESOURCE_GROUP_NAME = rg_name
    LOCATION = "eastus"
    rg_result = resource_client.resource_groups.create_or_update(RESOURCE_GROUP_NAME, { "location": LOCATION })
    return print(f"Provisioned resource group {rg_result.name}")
```

**Comment by Aman-Surkar** [comment]
***DAY 2***

TASK : Writing code to provision Storage Account.

Written Code to provision Storage Account. Storage Account gets created when the script is run.

<img width="523" alt="storage_cmd" src="https://user-images.githubusercontent.com/99606590/231657011-97899ef9-b767-4a9b-a99d-a379bf05e2ea.png">
<img width="718" alt="image" src="https://user-images.githubusercontent.com/99606590/231657237-4a40c528-e618-45c4-be55-f20d41d91977.png">

The code run efficiently as per the images above.

To Run the Script:

```
python Storage_Account.py
```
Script output:
Provisioned resource group PythonAzureExample-Storage-rg
Provisioned storage account pythonazuregems779890
Provisioned blob container pythongems

**Comment by Aman-Surkar** [comment]
***DAY 3***

TASK: Testing the Storage Code with different inputs

The code was modified to convert Storage Name input to lowercase as per the naming conventions of Azure Storage.

Output: The code runs fine with different inputs and the Storage Account is provision as per the inputs provided.

**Comment by VasudeoShruti** [comment]
**SUMMARY:**

- This git issue is used for tracking the efforts for automating Storage Creation on Azure using Python code. 
- The required test results has been attached with the git issue via screen shots.
- The working code has been pushed to git repo: https://github.com/VasudeoShruti/CloudCoders/pull/7

**Closing the issue since the needful has been done.**
