### ISSUE TITLE
Cloud Coders: Automate Database Creation from Azure Cloud

### ISSUE THREAD

**Issue by VasudeoShruti** [VasudeoShruti/CloudCoders#4]
This git issue is used for tracking the efforts for developing python script to Automate Azure Database.

**Comment by aditigupta14** [comment]
Wrote code for provisioning MySQL Server and database .
Tested my code with frontend.
Both server and database are provisioned using the code.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/55804312/231167025-1ee40a5a-3f1e-468e-9b55-f30a9c84a3f7.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/55804312/231167540-7e39182b-139f-4c92-810b-0f38fb004345.png)

This is how I am running my Python code:
python create_database.py

Script output:
Provisioned resource group
Provisioned MySQL server hackathonserver01
Provisioned MySQL database hackathondb01

**Comment by aditigupta14** [comment]
Day 3 

Solved few bugs.
Worked with frontend to handle errors.
Database is provisioned successfully.

![image](https://user-images.githubusercontent.com/55804312/231390821-e25bc9c0-890d-4424-a551-17e5e8b5ca5c.png)

This is how I am running my Python code:
python create_database.py

Script output:
Provisioned resource group
Provisioned MySQL server hackathonserver01
Provisioned MySQL database hackathondb01

**Comment by VasudeoShruti** [comment]
**SUMMARY:**

This git issue is used for tracking the efforts for automating database creation on Azure using Python code. 
The code is working & has been pushed to git repo:
https://github.com/VasudeoShruti/CloudCoders/pull/7

**Closing the issue since the needful has been done.**
