### ISSUE TITLE
Cloud Coders: Code Integration & End-2-End testing

### ISSUE THREAD

**Issue by VasudeoShruti** [VasudeoShruti/CloudCoders#5]
### **Integrating and Testing**

Integrating the Frontend and Backend Code along with testing will help to bring out more error and solve them before releasing. 
Following task will be completed under this issue:
- Integrating the Frontend and Backend code to make it work together.
- Each component will be Tested separately with different inputs to bring out vulnerabilities.

**Comment by Aman-Surkar** [comment]
TASK: To integrate code of all the 3 Services (Virtual Machine, Storage Provisioning, Database Provisioning).

The Backend code of all the 3 Services was integrated with the Frontend React UI. The Frontend and Backend was tested separately and also after Integration. The code was further modified with Error Handling to handle any error. 

We have also written code to create Log file that will maintain all the records whenever the code is run.

Further to ease and shorten the process of start the code, we have created batch files that will run the code, start and execute the steps that are required.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/99606590/231662357-3e49a4d2-6770-4b8b-87a2-f81b30d8623e.png">

<img width="960" alt="Frontend" src="https://user-images.githubusercontent.com/99606590/231661864-879146c5-791c-497b-8e74-b426d7052ac4.png">
<img width="960" alt="Azure VM" src="https://user-images.githubusercontent.com/99606590/231661885-061df4cf-7c5f-4071-a94b-09afd69d8c16.png">
<img width="960" alt="storageform" src="https://user-images.githubusercontent.com/99606590/231661913-ab3ff998-7909-4647-8b02-c585a780e9e3.png">
<img width="960" alt="database form" src="https://user-images.githubusercontent.com/99606590/231661930-6da2f8f5-1608-4f05-840d-7c041a4f9d44.png">

**Comment by VasudeoShruti** [comment]
**SUMMARY:**

- This git issue is used for tracking the efforts in integrating the various code components.
- The required test results has been attached with the git issue.
- The working code has been pushed to git repo: https://github.com/VasudeoShruti/CloudCoders/pull/7

**Closing the issue since the needful has been done.**
